---
title: "TAGC_manhattanplot"
author: "Sahar Mozaffari"
date: "3/8/2017"
output: html_document
---

```{r readinfiles, include=FALSE,  echo=FALSE}
library(qqman)
tab <- read.csv("TAGCpvaluesCarole.csv", header = T)
tab2 <- tab[,c(3,1,2,5)]
colnames(tab2) <- colnames(gwasResults)


```
#Bicolor manhattan plots to match slides

```{r bicolor_manhattanplot,  echo=FALSE}
manhattan(tab2, col = c("#F2CBA4","#97595C"), suggestiveline=F)
```

#Colored Manhattan plot to match low hanging fruit figure

```{r hangingfruit_manhattanplot, echo=FALSE}
manhattan(tab2, col = c("#67B2C7","#F2BC4B",
                        "#75C9B1","#FF6D48",
                        "#E79292","#8B3131",
                        "#546D34","#95A672",
                        "#F6CE1C","#E66921",
                        "#5A4390","#BE92AF",
                        "#EB0033","#26A9E0",
                        "#B6B2A8","#507F83",
                        "#2F4858","#DC4500",
                        "#F6AF1E","#FAE6C8",
                        "#AF8257","#D5BDAA"), suggestiveline = F)
```

```{r info,  echo=FALSE}

sessionInfo()
```

